import { Course } from '../models/course';
import { User } from '../models/user';

export const COURSES: Course[] = [
  {
    id: 1,
    name: 'Node.js',
    content: 'A basic Node.js course for beginners',
    author: 'Node.js Titan',
    authorId: 1,
    image: './assets/images/node.png',
    startDate: '12/08/2020',
    endDate: '12/11/2020',
    likes: 4,
    price: 80,
    sessions: 20,
    studentsMax: 20,
    certificate: false,
  },
  {
    id: 2,
    name: 'Drawing for beginners',
    content: 'A basic drawing course for beginners',
    author: 'Mrs Pencifly',
    authorId: 2,
    image: './assets/images/drawing.png',
    startDate: '12/06/2020',
    endDate: '12/08/2020',
    likes: 0,
    price: 0,
    sessions: 10,
    studentsMax: 20,
    certificate: false,
  },
  {
    id: 3,
    name: 'Advanced Python',
    content: 'An advanced Python course',
    author: 'the Pythonist',
    authorId: 3,
    image: './assets/images/python.jpg',
    startDate: '09/06/2020',
    endDate: '09/10/2020',
    likes: 3,
    price: 300,
    sessions: 25,
    studentsMax: 12,
    certificate: true,
  },
  {
    id: 4,
    name: 'Spanish for beginners',
    content: 'Comprehensive Spanish Lessons for beginners',
    author: 'Ola HOLa',
    authorId: 4,
    image: './assets/images/spanish.png',
    startDate: '09/06/2020',
    endDate: '09/10/2020',
    likes: 2,
    price: 70,
    sessions: 30,
    studentsMax: 10,
    certificate: true,
  },
  {
    id: 5,
    name: 'Cooking for begginers',
    content: 'Learn to cook 100 dishes from one type of meat',
    author: 'Dr. Chef',
    authorId: 5,
    image: './assets/images/cooking.jpg',
    startDate: '09/06/2020',
    endDate: '09/10/2020',
    likes: 2,
    price: 0,
    sessions: 30,
    studentsMax: 10,
    certificate: true,
  },
  {
    id: 6,
    name: 'Basics of political science',
    content: 'Basics of political science on the dark side',
    author: 'Vader',
    authorId: 6,
    image: './assets/images/politics.jpg',
    startDate: '09/06/2020',
    endDate: '09/10/2020',
    likes: 0,
    price: 100,
    sessions: 30,
    studentsMax: 10,
    certificate: true,
  },
  {
    id: 7,
    name: 'Negotiations for everyone',
    content: 'Start negotiating like a pro',
    author: 'GodDad',
    authorId: 7,
    image: './assets/images/peacetalk.jpg',
    startDate: '09/06/2020',
    endDate: '09/10/2020',
    likes: 0,
    price: 100,
    sessions: 30,
    studentsMax: 10,
    certificate: true,
  },
  {
    id: 8,
    name: 'A party maker\'s beginner course',
    content: 'Learn how to arrange deadly perfect parties',
    author: 'Sean',
    authorId: 8,
    image: './assets/images/parties.jpg',
    startDate: '09/06/2020',
    endDate: '09/10/2020',
    likes: 0,
    price: 0,
    sessions: 5,
    studentsMax: 10,
    certificate: false,
  },
];

export const USERS: User[] = [
  {
    id: 1,
    name: 'Ola HOla',
    image: './assets/user/user1.jpg',
    authoredCourses: [4],
    enrolledCourses: [2],
    likedCourses: [1, 3],
  },
  {
    id: 2,
    name: 'Node.js Titan',
    image: './assets/user/user2.jpg',
    authoredCourses: [1],
    enrolledCourses: [],
    likedCourses: [],
  },
  {
    id: 3,
    name: 'the Pythonist',
    image: './assets/user/user3.jpg',
    authoredCourses: [3],
    enrolledCourses: [2],
    likedCourses: [1, 3],
  },
  {
    id: 4,
    name: 'Mrs Pencifly',
    image: './assets/user/user4.jpg',
    authoredCourses: [2],
    enrolledCourses: [1],
    likedCourses: [],
  },
  {
    id: 5,
    name: 'Dr. Chef',
    image: './assets/user/user5.jpg',
    authoredCourses: [5],
    enrolledCourses: [1],
    likedCourses: [],
  },
  {
    id: 6,
    name: 'Vader',
    image: './assets/user/user6.jpg',
    authoredCourses: [6],
    enrolledCourses: [1],
    likedCourses: [5],
  },
  {
    id: 7,
    name: 'GodDad',
    image: './assets/user/user7.jpg',
    authoredCourses: [7],
    enrolledCourses: [1, 5],
    likedCourses: [5, 1, 4],
  },
  {
    id: 8,
    name: 'Sean',
    image: './assets/user/user8.jpg',
    authoredCourses: [8],
    enrolledCourses: [1, 7],
    likedCourses: [3, 1, 4],
  },
];

export const FOLLOWERS: {userId: number, followerId: number}[] = [
  {userId: 1, followerId: 2},
  {userId: 1, followerId: 3},
  {userId: 2, followerId: 4},
  {userId: 1, followerId: 4},
];


export const AUTH_USERS: {id: number, email: string, password: string}[] = [
  { id: 1, email: 'ola@mail.ru', password: 'ola1234' },
  { id: 2, email: 'titan@mail.ru', password: 'titan1234' },
  { id: 3, email: 'python@mail.ru', password: 'python1234' },
  { id: 4, email: 'pen@mail.ru', password: 'pen1234' },
  { id: 5, email: 'lecter@mail.ru', password: 'lecter1234' },
  { id: 6, email: 'dart@mail.ru', password: 'dart1234' },
  { id: 7, email: 'dad@mail.ru', password: 'dad1234' },
];
